version: '3.1'

services:
    cruel-db:
        image: mysql:8.0.27
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3309:3306'
        volumes:
            - ./dbdump/db:/docker-entrypoint-initdb.d
            - ./mysqldata:/var/lib/mysql:rw,delegated
        platform: linux/x86_64
networks:
    cruel:
        driver: bridge
