spring:
    jpa:
        org:
            hibernate:
                envers:
                    audit_table_suffix: _audits
                    revision_field_name: rev_id
                    # envers delete 기록 삭제는 레코드가 null로 표기되지만,
                    # delete 직전 해당 레코드의 필드를 남길 때 사용
                    store_data_at_delete: true
