spring:
    application:
        name: cruel-app-web
    profiles:
        active: local
        group:
            local: common, local
            develop: common, develop
            production: common, production
---
spring:
    config:
        activate:
            on-profile: common
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
---
spring:
    config:
        activate:
            on-profile: local, develop
springfox:
    documentation:
        swagger-ui:
            base-url: /api/docs
        enabled: true
---
spring:
    config:
        activate:
            on-profile: production
springfox:
    documentation:
        enabled: false
---
server:
    port: 8080

cruel:
    jwt:
        secret: "zmfndjfdlsxjsjfxhzmsdmsaucwkrksjadjdigkseksmsepanjswlwkfahfmrpRtekrmsidrlfrpgkwk"
        expiry-seconds: 3600 # 1h
    secret-key: "ThisIsTempSecretKey"
